---@alias EventID number
---@alias EventName string

--- Basic class for all the musical event.
--- An event can emit a callback function
--- (e.g. outputting a message or changing the internal state).
--- Event can "act out" (be played) when passed to `Player`.
--- This happens by playing all the players within event's `.players`.
--- An event itself can rule over other players with their own events.
---@class (exact) Event: Metatable<Event>
---@field new fun(name?:string): Event
---properties
---@field id EventID When event was created.
---@field name EventName More "user-friendly" name of an event (if given).
---@field duration Miliseconds How long does the event lasts (this is usually set by Player).
---@field emitters {string:Emitter} Table of objects that need to be called when this event is triggered. Iterate over it using pairs(). Timed events are stored under number index and other emmiters at string.
---@field players {number:Player}
---methods
---@field tostring fun(self:Event): string # Turn an event into a string representation (e.g. for logging).
---@field emit fun(self:Event, o:Score) # Do this when event is called (e.g. output something from an pd box's outlet – this is defined in emit_callback).
---@field merge fun(self:Event, other:Event, time_offset:number, overdub?:boolean) # Merges an `event` with the `other` one. All `player`s are copied and duration is recalculated. When `overdub`bing, `player`s starting within time of the other `event`'s duration are removed.
