--[[    Main object.    ]]
---@class (exact) Score: PDObject
---properties
---@field recorder Recorder
---@field players { [PlayerName]: Player }
---@field tracks { [EventName]: Event } # Events with names accessible from pd interface.
---private methods
---@field get_player fun(self: Score, player_label: PlayerName|PlayerID): Player|nil
---@field get_track fun(self: Score, track_label: EventName|EventID): Event|nil # Returns the track named track_name. If not such track exists yet, makes a new one.
---public methods
---@field in_1_info fun(self: Score, atoms: { [1]: EventID|EventName}): nil
---@field in_1_midi fun(self: Score, bytes: MidiByte[]): nil
---@field in_1_play fun(self: Score, atoms: { [1]: EventName, [2]: Speed, [3]: integer}): nil
---@field in_1_reload fun(self: Score): nil
---@field in_1_record fun(self: Score, atoms: { [1]: EventName, [2]: Speed }): nil
